language: bash
sudo: required
dist: trusty

otp_release:
    - 19.2

addons:
  apt:
    packages:
    - squashfs-tools

env:
    - ERLANG_VERSION=19.2 ELIXIR_VERSION=1.4.5 MIX_TARGET=rpi0

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
        sudo dpkg -i esl-erlang_$ERLANG_VERSION-1~ubuntu~trusty_amd64.deb;
        wget https://github.com/fhunleth/fwup/releases/download/v0.15.1/fwup_0.15.1_amd64.deb;
        sudo dpkg -i fwup_0.15.1_amd64.deb;
      fi
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
    - mix local.hex --force
    - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
    - mix deps.get
    - mix compile
    - mix firmware
    # - mix firmware.push $NERVES_SSH_DEST --port $NERVES_SSH_PORT
