language: erlang

otp_release:
    - 19.2

env:
    - ELIXIR_VERSION=1.4.5 MIX_TARGET=rpi0

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
    - mix local.hex --force
    - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
    - mix deps.get
    - mix compile
    - mix firmware
    # - mix firmware.push $NERVES_SSH_DEST --port $NERVES_SSH_PORT
